version: '1.0'
name: pipeline-20231016
displayName: pipeline-20231016
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
  pr:
    branches:
      precise:
        - master
stages:
  - name: stage-6d8708d4
    displayName: 发版
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.2.0.0
        autoIncrement: false
        notify: []
        strategy:
          retry: '0'
        dependsOn: publish_general_artifacts
strategy:
  cloneDepth: 1
  blocking: false
